const lessons=[
{day:'Lunes',title:'An Interview About Listening Skills',url:'https://learnenglish.britishcouncil.org/free-resources/listening/b1/interview-about-listening-skills',goal:'Comprender consejos sobre listening.',keys:['listening','skills','interview','understand']},
{day:'Martes',title:'Chatting About a Series',url:'https://learnenglish.britishcouncil.org/free-resources/listening/b1/chatting-about-series',goal:'Comprender una charla informal.',keys:['series','watch','episode','character']},
{day:'Miércoles',title:'A Phone Call from a Customer',url:'https://learnenglish.britishcouncil.org/free-resources/listening/b1/a-phone-call-from-a-customer',goal:'Comprender una llamada.',keys:['customer','phone','order','problem']},
{day:'Jueves',title:'Organising Your Time',url:'https://learnenglishteens.britishcouncil.org/skills/listening/b1-listening/organising-your-time',goal:'Comprender organización del tiempo.',keys:['time','organise','schedule','plan']},
{day:'Viernes',title:'Difficult Situations',url:'https://learnenglishteens.britishcouncil.org/skills/listening/b1-listening/difficult-situations',goal:'Comprender consejos.',keys:['situation','problem','advice','difficult']},
{day:'Sábado',title:'British Council B1 Library',url:'https://learnenglish.britishcouncil.org/free-resources/listening/b1',goal:'Repaso libre.',keys:['listening','practice','audio','b1']}
];let state=JSON.parse(localStorage.getItem('coachV5')||'{"selected":0,"done":{},"dictations":[],"vocab":[],"dark":true,"quizScores":[]}');if(state.dark)document.body.classList.add('dark');function save(){localStorage.setItem('coachV5',JSON.stringify(state))}function doneCount(){return Object.keys(state.done).length}function getTodayIndex(){let d=new Date().getDay();return d===0?5:d-1}
function go(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.navBtn').forEach(b=>b.classList.remove('active'));let map={today:0,lessons:1,practice:2,test:3,progress:4,certificate:5,help:6};document.querySelectorAll('.navBtn')[map[id]].classList.add('active');render()}
function renderToday(){let l=lessons[getTodayIndex()];document.getElementById('todayTitle').textContent=`${l.day}: ${l.title}`}
function renderLessons(){let box=document.getElementById('lessonList');box.innerHTML='';lessons.forEach((l,i)=>{let div=document.createElement('article');div.className='lesson';div.innerHTML=`<span class="status">${state.done[i]?'Completada ✅':'Pendiente'}</span><h3>${l.day}: ${l.title}</h3><p class="muted">${l.goal}</p><button class="btn primary" onclick="selectLesson(${i})">Practicar</button><a class="btn soft" href="${l.url}" target="_blank">Abrir audio</a>`;box.appendChild(div)})}
function selectLesson(i){state.selected=i;save();go('practice')}function renderPractice(){let l=lessons[state.selected]||lessons[0];document.getElementById('practiceTitle').textContent=`${l.day}: ${l.title}`;document.getElementById('practiceGoal').textContent=l.goal;document.getElementById('audioBtn').href=l.url;document.getElementById('lessonStatus').textContent=state.done[state.selected]?'Completada':'Pendiente';renderQuiz()}
function completeLesson(){state.done[state.selected]=true;save();render();alert('¡Lección completada!')}
function saveVocab(){let txt=document.getElementById('vocabInput').value.trim();if(!txt){alert('Escribe vocabulario primero.');return}let words=txt.split(',').map(x=>x.trim()).filter(Boolean);state.vocab.push(...words);save();document.getElementById('vocabFeedback').textContent=`Guardaste ${words.length} palabras. Total: ${state.vocab.length}.`;document.getElementById('vocabInput').value='';render()}
function saveDictation(){let text=document.getElementById('dictation').value.trim();if(!text){alert('Escribe una frase primero.');return}let l=lessons[state.selected]||lessons[0],low=text.toLowerCase(),hits=l.keys.filter(k=>low.includes(k)).length;state.dictations.push({date:new Date().toLocaleDateString(),lesson:l.title,text,score:hits});save();document.getElementById('dictationFeedback').textContent=`Guardado. Palabras clave detectadas: ${hits}/${l.keys.length}.`;render()}
function clearDictation(){document.getElementById('dictation').value='';document.getElementById('dictationFeedback').textContent=''}
function renderQuiz(){let l=lessons[state.selected]||lessons[0];document.getElementById('testTitle').textContent=`Test: ${l.title}`;let qs=[['¿Entendiste la idea general?','Sí'],['¿Reconociste 5 palabras?','Sí'],['¿Pudiste hacer shadowing?','Sí']];let box=document.getElementById('quizBox');box.innerHTML='';qs.forEach((q,i)=>{let div=document.createElement('div');div.className='question';div.innerHTML=`<p><b>${i+1}.</b> ${q[0]}</p><label><input type="radio" name="q${i}" value="1"> Sí</label><br><label><input type="radio" name="q${i}" value="0"> No</label>`;box.appendChild(div)})}
function gradeQuiz(){let score=0;[0,1,2].forEach(i=>{let a=document.querySelector(`input[name="q${i}"]:checked`);if(a&&a.value==='1')score++});let pct=Math.round(score/3*100);state.quizScores.push({pct,date:new Date().toLocaleDateString()});save();document.getElementById('quizResult').textContent=`Resultado: ${pct}%. ${pct>=70?'Aprobado. Muy bien.':'Repite el audio y vuelve a intentar.'}`;render()}
function renderProgress(){let count=doneCount(),pct=Math.round(count/lessons.length*100);document.getElementById('streak').textContent=count;document.getElementById('miniPercent').textContent=pct+'%';document.getElementById('percent').textContent=pct+'%';document.getElementById('ring').style.setProperty('--pct',pct+'%');document.getElementById('progressText').textContent=`${count} de ${lessons.length} lecciones completadas`;document.getElementById('certDone').textContent=count;document.getElementById('certDict').textContent=state.dictations.length;document.getElementById('certPct').textContent=pct+'%';let h=document.getElementById('history');h.innerHTML='';state.dictations.slice().reverse().forEach(d=>{let li=document.createElement('li');li.textContent=`${d.date} · ${d.lesson}: ${d.text}`;h.appendChild(li)});let badges=[['🏁','Primer paso','Completa 1 lección',count>=1],['🔥','Constancia','Completa 3 lecciones',count>=3],['🏆','Semana B1','Completa 6 lecciones',count>=6],['📝','Dictado activo','Guarda 3 dictados',state.dictations.length>=3],['🎧','Oído entrenado','Guarda 10 palabras',state.vocab.length>=10],['✅','Test B1','Aprueba 1 mini test',state.quizScores.some(x=>x.pct>=70)]];let b=document.getElementById('badges');b.innerHTML='';badges.forEach(x=>{let div=document.createElement('div');div.className='badge '+(x[3]?'':'locked');div.innerHTML=`<div style="font-size:36px">${x[3]?x[0]:'🔒'}</div><b>${x[1]}</b><p class="muted">${x[2]}</p>`;b.appendChild(div)})}
function resetAll(){if(confirm('¿Reiniciar progreso?')){state.done={};state.dictations=[];state.vocab=[];state.quizScores=[];save();render()}}document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('dark');state.dark=document.body.classList.contains('dark');save()};let recognition;function startSpeech(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){document.getElementById('speechBox').textContent='Tu navegador no permite reconocimiento de voz.';return}recognition=new SR();recognition.lang='en-US';recognition.interimResults=true;recognition.onresult=e=>{let txt='';for(let i=0;i<e.results.length;i++)txt+=e.results[i][0].transcript+' ';document.getElementById('speechBox').textContent=txt};recognition.start()}function stopSpeech(){if(recognition)recognition.stop()}function render(){renderToday();renderLessons();renderPractice();renderProgress()}if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js?v=5').catch(()=>{}))}render();