const lessons=[["Lunes","An Interview About Listening Skills","https://learnenglish.britishcouncil.org/free-resources/listening/b1/interview-about-listening-skills",["listening","skills","interview","understand"]],["Martes","Chatting About a Series","https://learnenglish.britishcouncil.org/free-resources/listening/b1/chatting-about-series",["series","watch","episode","character"]],["Miércoles","A Phone Call from a Customer","https://learnenglish.britishcouncil.org/free-resources/listening/b1/a-phone-call-from-a-customer",["customer","phone","order","problem"]],["Jueves","Organising Your Time","https://learnenglishteens.britishcouncil.org/skills/listening/b1-listening/organising-your-time",["time","organise","schedule","plan"]],["Viernes","Difficult Situations","https://learnenglishteens.britishcouncil.org/skills/listening/b1-listening/difficult-situations",["situation","problem","advice","difficult"]],["Sábado","British Council B1 Library","https://learnenglish.britishcouncil.org/free-resources/listening/b1",["listening","practice","audio","b1"]]];
let state=JSON.parse(localStorage.getItem("coachPremiumV3")||'{"selected":0,"done":{},"dictations":[],"dark":true}');if(state.dark)document.body.classList.add("dark");function save(){localStorage.setItem("coachPremiumV3",JSON.stringify(state))}function count(){return Object.keys(state.done).length}
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));let m={lessons:0,practice:1,progress:2,badges:3,help:4};document.querySelectorAll(".tab")[m[id]].classList.add("active");render()}
function renderLessons(){let box=document.getElementById("lessonList");box.innerHTML="";lessons.forEach((l,i)=>{let d=state.done[i];let div=document.createElement("article");div.className="lesson";div.innerHTML=`<span class="status">${d?"Completada ✅":"Pendiente"}</span><h3>${l[0]}: ${l[1]}</h3><p class="muted">Audio oficial British Council · 30 minutos.</p><button class="btn primary" onclick="selectLesson(${i})">Practicar</button><a class="btn ghost" href="${l[2]}" target="_blank">Abrir audio</a>`;box.appendChild(div)})}
function selectLesson(i){state.selected=i;save();showView("practice")}
function renderPractice(){let l=lessons[state.selected];document.getElementById("currentLesson").textContent=l[0]+": "+l[1];document.getElementById("lessonUrl").href=l[2]}
function completeLesson(){state.done[state.selected]=true;save();render();alert("¡Lección completada!")}
function saveDictation(){let text=document.getElementById("dictation").value.trim();if(!text){alert("Escribe una frase primero.");return}let l=lessons[state.selected],low=text.toLowerCase(),hits=l[3].filter(k=>low.includes(k)).length;state.dictations.push({date:new Date().toLocaleDateString(),lesson:l[1],text,score:hits});save();document.getElementById("dictationResult").textContent=`Guardado. Palabras clave: ${hits}/${l[3].length}.`;render()}
function clearDictation(){document.getElementById("dictation").value="";document.getElementById("dictationResult").textContent=""}
function renderProgress(){let done=count(),pct=Math.round(done/lessons.length*100);document.getElementById("streak").textContent=done;document.getElementById("percentMini").textContent=pct+"%";document.getElementById("percent").textContent=pct+"%";document.getElementById("ring").style.setProperty("--pct",pct+"%");document.getElementById("progressText").textContent=`${done} de ${lessons.length} lecciones completadas`;let h=document.getElementById("history");h.innerHTML="";state.dictations.slice().reverse().forEach(d=>{let li=document.createElement("li");li.textContent=`${d.date} · ${d.lesson}: ${d.text}`;h.appendChild(li)})}
function renderBadges(){let done=count(),data=[["Primer paso","Completa 1 lección",done>=1],["Constancia","Completa 3 lecciones",done>=3],["Semana B1","Completa 6 lecciones",done>=6],["Dictado activo","Guarda 3 dictados",state.dictations.length>=3]];let b=document.getElementById("badgeList");b.innerHTML="";data.forEach(x=>{let div=document.createElement("div");div.className="badge "+(x[2]?"":"locked");div.innerHTML=`<div style="font-size:42px">${x[2]?"🏆":"🔒"}</div><h3>${x[0]}</h3><p class="muted">${x[1]}</p>`;b.appendChild(div)})}
function resetProgress(){if(confirm("¿Reiniciar todo?")){state.done={};state.dictations=[];save();render()}}
document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("dark");state.dark=document.body.classList.contains("dark");save()};let recog;function startSpeech(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){document.getElementById("speechOutput").textContent="Tu navegador no permite reconocimiento de voz.";return}recog=new SR();recog.lang="en-US";recog.interimResults=true;recog.onresult=e=>{let t="";for(let i=0;i<e.results.length;i++)t+=e.results[i][0].transcript+" ";document.getElementById("speechOutput").textContent=t};recog.start()}function stopSpeech(){if(recog)recog.stop()}function render(){renderLessons();renderPractice();renderProgress();renderBadges()}if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}))}render();